### ISSUE TITLE
Annotation of cell clusters

### ISSUE THREAD

**Issue by teunbrand** [HeleneKretzmer/TLS#1]
Hello Helene,

Congratulations on the great TLS paper, it was an exciting read and the data looks beautiful!
I was wondering whether perhaps you would consider making your annotation of cells types/clusters available for the scRNAseq data? Maybe I wasn't looking carefully enough in the supplemental data or on GEO and I apologise if this is the case, but I couldn't find these assignments. We're interested in comparing your data to some we've collected and it would be helpful to us if we'd know what cells/cell-barcodes belong to what cluster.

Thank you for your attention and best wishes,
Teun

**Comment by HeleneKretzmer** [comment]
Hello Teun,

Thank you very much and also for your interest in the data. We are happy to share these data - I uploaded a metadata file to the Seurat folder containing the sample time point, the barcode, UMAP coordinates, and the cell state (cluster). Please let me know if something is missing.

Have a nice holiday and best wishes,
Helene

**Comment by teunbrand** [comment]
Hello Helene,

Thank you for uploading the metadata, this is perfect! It is exactly the kind of information I was looking for and will help us tremendously. 

Thanks again and happy holiday,
Teun
